In [1]:
# Importing numpy package
import numpy as np

### [**numpy.random.randint**](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html)

In [2]:
# Generate 10 random integers
np.random.randint(51,101,50)

array([ 81,  68,  76,  67,  78,  92,  84,  59,  55,  88,  95, 100,  89,
        85,  72,  81,  83,  92,  87,  52,  97,  91,  60,  98,  80,  84,
        61,  80,  86,  77,  98,  92,  60,  78,  76,  79,  81,  61,  99,
        82,  66,  98,  58,  84,  86,  56,  68,  67,  58,  83])

In [3]:
# Generate 10 integers between 1 to 50
np.random.randint(1,50,10)

array([31, 13,  8, 32, 29, 19, 20, 39, 31, 31])

### **random.seed**
What of we want to fix the random generation of the number. Then we can fix the initial point of random number generation. So, basically we use numpy.random.seed to fix the initial point of the some algorithm.

In [6]:
# Creating same random number using random.seed
np.random.seed(13)
np.random.randint(1,50,3)

array([19, 49, 11])

In [7]:
# Create an array of numpy integer from 1 to 50
x1 = np.arange(1,51)
x1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [11]:
# Shuffling the array randomly using random.shuffle
np.random.shuffle(x1)
x1

array([18, 16, 30, 36, 14, 26, 46, 40, 29,  5,  7, 13, 38,  4, 21, 32,  3,
        2, 42, 24,  6, 50, 34, 23, 27, 11, 33, 28, 31, 22, 44, 25, 19,  1,
       17, 45,  8, 15, 35, 20, 43, 10, 39, 12, 48, 47, 41,  9, 49, 37])

In [13]:
# Sorting the array using sort function
x1.sort()
x1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [14]:
# Sortng in reverse order
x1[::-1]

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

**Using numpy.random.choice to generate random options from a given choice.**

In [15]:
# Importing choise from numpy.random
from numpy.random import choice

In [16]:
choice(["ROCK","PAPER","SCISSOR"],8)

array(['ROCK', 'SCISSOR', 'SCISSOR', 'ROCK', 'PAPER', 'ROCK', 'ROCK',
       'PAPER'], dtype='<U7')

In [19]:
# Using np.random.choice
x2 = np.random.choice(x1, size=100)
print(x2)

[10 47 19  9 38 15 13  3 49 45 45 15 27 49 19 49  6 25 31 10 29 41 26 47
 27 41 31  6 24 15 40 19 36 21 21  6  5 15 44  2 50 39 16 13 23 25 25 43
 20 17 39 10 32  3  5 44 46 25  7 16 17  9 42 15 33 36 32 47 22  4 28 33
 38 21 45 24 16 47 35 42 21 29 40 43 12 32 16  2 35 25 34 28 34 31 50 32
 13 37 43 19]


In [21]:
len(np.unique(x2))

43

In [20]:
# Removing duplicate elements using unique function
np.unique(x2, return_index = True, return_counts = True)

(array([ 2,  3,  4,  5,  6,  7,  9, 10, 12, 13, 15, 16, 17, 19, 20, 21, 22,
        23, 24, 25, 26, 27, 28, 29, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 49, 50]),
 array([39,  7, 69, 36, 16, 58,  3,  0, 84,  6,  5, 42, 49,  2, 48, 33, 68,
        44, 28, 17, 22, 12, 70, 20, 18, 52, 64, 90, 78, 32, 97,  4, 41, 30,
        21, 62, 47, 38,  9, 56,  1,  8, 40]),
 array([2, 2, 1, 2, 3, 1, 2, 3, 1, 3, 5, 4, 2, 4, 1, 4, 1, 1, 2, 5, 1, 2,
        2, 2, 3, 4, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 3, 2, 3, 1, 4, 3, 2]))

# **This array show the number in array: **
(array([ 2,  3,  4,  5,  6,  7,  9, 10, 12, 13, 15, 16, 17, 19, 20, 21, 22,
        23, 24, 25, 26, 27, 28, 29, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 49, 50]),

# **THis array show the index: **
 array([39,  7, 69, 36, 16, 58,  3,  0, 84,  6,  5, 42, 49,  2, 48, 33, 68,
        44, 28, 17, 22, 12, 70, 20, 18, 52, 64, 90, 78, 32, 97,  4, 41, 30,
        21, 62, 47, 38,  9, 56,  1,  8, 40]),

# **This array show the repetation: **
 array([2, 2, 1, 2, 3, 1, 2, 3, 1, 3, 5, 4, 2, 4, 1, 4, 1, 1, 2, 5, 1, 2,
        2, 2, 3, 4, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 3, 2, 3, 1, 4, 3, 2]))