**Numpy**

In [4]:
height=[1.43,1.45,1.76,1.34,1.7]
weight=[65.4,47.34,49.00,52.23,62.23]

In [ ]:
#calculate BMI using list
bgi = weight/height**2

NameError: ignored

In [1]:
#import numpy
import numpy as np

In [7]:
# Convert list into numpay
np_height=np.array(height)
np_weight=np.array(weight)

In [ ]:
type(np_height)

numpy.ndarray

In [ ]:
type(height)

list

In [9]:
# calculate BMI using numpy
np_BMI = np_weight/np_height**2
np_BMI

array([31.98200401, 22.51605232, 15.81869835, 29.0877701 , 21.53287197])

### **Why it worked in Numpy?**
NumPy provides an N-dimension array type, the ndarry, which describes a collection of "items" of the same type.

In [2]:
x = np.array([1.0,"is",True])

In [3]:
type(x)

numpy.ndarray

In [ ]:
# Addition in lists & NumPy

In [6]:
# Add list
x = height+weight
x

[1.43, 1.45, 1.76, 1.34, 1.7, 65.4, 47.34, 49.0, 52.23, 62.23]

In [8]:
# Using NumPy
y = np_height+np_weight
y

array([66.83, 48.79, 50.76, 53.57, 63.93])

In [10]:
# NumPy Subsetting
np_BMI

array([31.98200401, 22.51605232, 15.81869835, 29.0877701 , 21.53287197])

In [11]:
# Index
np_BMI[1]

22.516052318668255

In [12]:
# Boolen
np_BMI>22

array([ True,  True, False,  True, False])

In [13]:
# Single Value
np_BMI[np_BMI>22]

array([31.98200401, 22.51605232, 29.0877701 ])