In [6]:
# Importing the package
import numpy as np

### [**numpy.arange**](https://numpy.org/doc/stable/reference/generated/numpy.arange.html)

In [7]:
# Generating range upto 15
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
x = np.arange(1,16)

In [ ]:
type(x)

numpy.ndarray

In [ ]:
# Printing the variable of the range
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
# Checking if the elements are greater than 6
print(x>6)

[False False False False False False  True  True  True  True  True  True
  True  True  True]


In [ ]:
# Another single condition
print(x == 6)

[False False False False False  True False False False False False False
 False False False]


In [ ]:
# Double condition using &
x1 = (x==6) & (x==7)
print(x1)

[False False False False False False False False False False False False
 False False False]


In [9]:
# Double condition using |
x2 = (x==6) | (x==7)
print(x2)

[False False False False False  True  True False False False False False
 False False False]


In [10]:
# Using ~ operator for oppositing
print(~x2)

[ True  True  True  True  True False False  True  True  True  True  True
  True  True  True]


In [12]:
# Slicing all the elements if the elements are greater than 6
x[x>6]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
# Slicing all the elements if the elements are less than 5
x[x<5]

array([1, 2, 3, 4])